#!/usr/bin/env bash
#https://github.com/Aylur/dotfiles/blob/eww/.config/eww/scripts/osd

# function STATE {
#   eww windows | grep osd | awk '{print substr ($0, 0, 1)}'
# }
#
# if [[ $1 == 'close' ]]; then
#   if [[ $(STATE) == '*' ]]; then eww close osd; fi
# else
#     eww update osd="{ \"icon\": \"$1\", \"value\": \"$2\" }"
#     if [[ $(STATE) != '*' ]]; then eww open osd; fi
#     sleep 4
#     if [[ $(STATE) == '*' ]]; then eww close osd; fi
# fi

eww update osd="{ \"icon\": \"$1\", \"value\": \"$2\" }"
eww open osd --duration 1750
