#!/usr/bin/env bash

ICON="󰃠"
function BRIGHTNESS {
  brightnessctl | grep "Current brightnes" | cut -d " " -f4 | grep -o "[0-9]*"
}

if [[ $1 == 'up' ]]; then
  brightnessctl set 5%+
  bash ~/.config/eww/launchers/osd $ICON $(BRIGHTNESS)
fi

if [[ $1 == 'down' ]]; then
  brightnessctl set 5%-
  bash ~/.config/eww/launchers/osd $ICON $(BRIGHTNESS)
fi
