[buildPlans.iosevka-eos]
family = "Iosevka Comfy"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-eos.variants.design]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-g = "toothless-corner-serifless-hookless"
capital-q = "crossing-curly-tailed"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
a = "single-storey-earless-rounded-tailed"
d = "toothless-rounded-serifless"
i = "flat-tailed"
j = "serifless"
k = "curly-serifless"
l = "flat-tailed"
x = "curly-serifless"
z = "curly-serifless"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-ef = "cursive"
zero = "tall-slashed"
four = "open-non-crossing"
six = "closed-contour"
eight = "crossing-asymmetric"
brace = "curly-flat-boundary"
number-sign = "slanted"
at = "fourfold-solid-inner"
dollar = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "corner"
lig-ltgteq = "slanted"
lig-neq = "vertical-dotted"
lig-equal-chain = "without-notch"
