#!/bin/bash
  data=`acpi | grep 'Battery 1'`
 value=`echo $data | grep -o '[0-9]*%' | grep -o '[0-9]*'`
status=`echo $data | grep -o Discharging`
   eta=`echo $data | cut -d' ' -f5-`

if [ "$status" != "Discharging" ]; then
	icon="󰂄"
else
	case 1 in
		$(($value>=95)))icon="󰁹";;
		$(($value>=85))) icon="󰂂";;
		$(($value>=75))) icon="󰂁";;
		$(($value>=65))) icon="󰂀";;
		$(($value>=55))) icon="󰁿";;
		$(($value>=45))) icon="󰁾";;
		$(($value>=35))) icon="󰁽";;
		$(($value>=25))) icon="󰁼";;
		$(($value>=15))) icon="󰁻";;
		$(($value>=5))) icon="󰁺";;
		*) icon="󰂎";;
	esac 
fi

echo "{ \"icon\": \"$icon\", \"value\": \"$value\", \"eta\": \"$eta\"}"
