#!/usr/bin/env bash
#swaync-client -swb | stdbuf -o0 jq --raw-output .text | stdbuf -o0 sed "s/0/󰎟/;s/1/󰲠/;s/2/󰲢/;s/3/󰲤/;s/4/󰲦/;s/5/󰲨/;s/6/󰲪/;s/7/󰲬/;s/8/󰲮/;s/9/󰲰/"

handle() {
	case $1 in
		0) echo "󰍡";;
		*) echo "󰍢";;
	esac
}

swaync-client -swb | stdbuf -o0 jq --raw-output .text | while read -r line; do handle "$line"; done
