#!/bin/bash
echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
if [[ $? -eq 0 ]]; then
	connection_type="`ip route get 8.8.8.8 | grep -Po 'dev \K\w+' | grep -qFf - /proc/net/wireless && echo wireless || echo wired`"
	if [[ $connection_type -eq "wireless" ]]; then
		signal_strength=`awk 'NR==3 {sub(/\./, "", $3); print $3}' /proc/net/wireless`
		if [[ $signal_strength -eq 100 ]]; then
			icon="󰤨"
		elif [[ $signal_strength -gt 75 ]]; then
			icon="󰤥"
		elif [[ $signal_strength -gt 50 ]]; then
			icon="󰤢"
		elif [[ $signal_strength -gt 25 ]]; then
			icon="󰤟"
		else
			icon="󰤯"
		fi
		value="wireless"
	else
		icon="󰈀"
		value="wired"
	fi
else
	icon="󰤭"
	value="off"
fi
echo "{\"icon\": \"$icon\", \"value\": \"$value\"}"
